# Generated by Django 4.2.11 on 2024-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True)),
                ('role', models.CharField(blank=True, choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20, null=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
