# Generated by Django 4.2.11 on 2024-05-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0005_remove_video_liked_user'),
        ('demand', '0004_remove_demand_liked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('已创建', '已创建'), ('已确认', '已确认'), ('已废弃', '已废弃')], max_length=255, null=True)),
                ('demand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='demand.demand')),
                ('video', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='bid', to='video.video')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
    ]
