# Generated by Django 4.2.11 on 2024-05-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_video_liked_user'),
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cover_addrs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('已创建', '已创建'), ('已确认', '已确认'), ('已废弃', '已废弃')], default='已创建', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='video.video'),
        ),
    ]
