# Generated by Django 4.2.11 on 2024-05-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_bid_cover_addrs_alter_bid_status_alter_bid_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='video',
        ),
        migrations.AddField(
            model_name='bid',
            name='video_addr',
            field=models.JSONField(null=True),
        ),
    ]
