# Generated by Django 4.2.11 on 2024-06-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0006_remove_demand_final_price_remove_demand_final_video'),
        ('bid', '0004_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='demand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='demand.demand'),
        ),
    ]
