# Generated by Django 4.2.11 on 2024-05-07 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_video_liked_user_video_played_alter_video_creator'),
        ('demand', '0002_demand_liked_user_alter_demand_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='final_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_demand', to='video.video'),
        ),
        migrations.AddField(
            model_name='demand',
            name='stared_user',
            field=models.ManyToManyField(blank=True, related_name='stared_demands', to=settings.AUTH_USER_MODEL),
        ),
    ]
