# Generated by Django 4.2.11 on 2024-05-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_demand_final_price_demand_final_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='liked_user',
        ),
    ]
