# Generated by Django 4.2.11 on 2024-05-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_remove_demand_liked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
