# Generated by Django 4.2.11 on 2024-06-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_demand_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='final_video',
        ),
    ]
