# Generated by Django 4.2.11 on 2024-05-07 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand', '0003_demand_final_price_demand_final_video_and_more'),
        ('video', '0003_video_liked_user_video_played_alter_video_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stared_user',
            field=models.ManyToManyField(blank=True, related_name='stared_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='wanted_demands',
            field=models.ManyToManyField(blank=True, related_name='wanted_videos', to='demand.demand'),
        ),
    ]
