# Generated by Django 4.2.11 on 2024-05-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_stared_user_video_wanted_demands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liked_user',
        ),
    ]
